version: '3.8'

services:
  # Название нашего сервиса
  mongo:
    # Берем официальный образ MongoDB.
    image: mongo:latest
    # Даем нашему контейнеру понятное имя, чтобы его было легко найти в списке контейнеров.
    container_name: crypto_mongo
    # Пробрасываем порты. Мы "связываем" порт 27017 внутри контейнера
    # с портом 27017 на нашем компьютере (хост-машине).
    # Это позволяет нашему Python-приложению, запущенному на хосте,
    # подключаться к MongoDB в контейнере по адресу localhost:27017.
    ports:
      - "27017:27017"
    # Мы создаем "именованный том" (named volume).
    # Это специальное хранилище, управляемое Docker, которое "переживет" удаление контейнера.
    volumes:
      - mongo_data:/data/db
    # Политика перезапуска. `always` означает, что Docker будет автоматически
    # перезапускать контейнер, если он упадет, или после перезагрузки компьютера.
    restart: always

# Здесь мы объявляем наш именованный том.
volumes:
  mongo_data:
